### ISSUE TITLE
Use 7zip to create bundle in Github action for releases 

### ISSUE THREAD

**Issue by cderv** [rstudio/tinytex#372]
Following https://github.com/yihui/tinytex/commit/48f417306bbe02d718e684036e3c53648b3dda75#commitcomment-73482170 as it seems on Windows `Compress-Archive` will not include hidden files;

**Comment by yihui** [comment]
Yes, let's use 7zip instead. Thanks!

**Comment by yihui** [comment]
Yes, I use Google Chrome (`Version 101.0.4951.64 (Official Build) (x86_64)`), and I don't get the warning when I download or extract them on macOS. Not sure if this is specific to Windows.

**Comment by cderv** [comment]
Ok. I don't find any information on this, so we'll see if we have report or not. I'll go with it.

**Comment by cderv** [comment]
In fact I forgot to check the hidden file thing... It does not seem to be included in the bundles 🤔 
It is locally when I tried the command line on my Windows. I need to check that again.

**Comment by cderv** [comment]
Ok I think this is because it is not in the right place: 
https://github.com/rstudio/tinytex/blob/48f417306bbe02d718e684036e3c53648b3dda75/tools/install-windows.bat#L46

I did not see that first in the comment of the commit but the hidden file is create in `%APPDATA%` instead of `%APPDATA%/TinyTeX`  where I think it should be. 

i'll fix this

**Comment by yihui** [comment]
Oh good catch! Thanks!

**Comment by cderv** [comment]
Ok this is modified in https://github.com/rstudio/tinytex/commit/9c738056965f9dc9a0d28c97aee3aca692169347 and tested in my fork. The hidden file will be included now.
