### ISSUE TITLE
Add latexindent and texcount by default

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/tinytex#378]
## Rationales

1. `tinytex` is used in `Quarto`.

1. `quarto-vscode` depends on `LaTeX Workshop` VSCode extension.

1. `LaTeX Workshop` requires `latexindent` for formatting tex document and `texcount` for word count.

It would be much easier to bundle these packages by default for `quarto-vscode`.

**Comment by yihui** [comment]
@jooyoungseo Thanks for the suggestion!

@jjallaire We just need to add these packages to `tools/pkgs-yihui.txt` here, right?

**Comment by jjallaire** [comment]
Yes, `tools/pkgs-yihui.txt` is the right one!
