### ISSUE TITLE
Update build workflow to tinitex artifact

### ISSUE THREAD

**Issue by cderv** [rstudio/tinytex#383]
See https://github.com/quarto-dev/quarto-cli/pull/2149#event-7269274345

**Comment by yihui** [comment]
Do you have time to work on this today? The monthly release of TinyTeX will take place tomorrow. If you don't have time, I can give it a try. I guess it shouldn't be hard.

**Comment by cderv** [comment]
Arg... I forgot that. We indeed have 15 hours. 😓 

Let me give a quick try to adapt the code for Pandoc devel. I'll then hand it up to you after that.

**Comment by cderv** [comment]
First feedback : 

Quarto workflow will package one Zip for all OS and not one bundle per OS. This means we need to download, unzip and repackage per OS to the current format  (zip, tar.gz and tgz)

Or we need to do three packages (so 3 artifacts) on Quarto workflow instead of pushing to one artifact. (which creates one zip). 
We would then do like with Pandoc devel and download the artifact for each OS as we run Linux Windows and Mac. 

I would say the second option is better long term. What do you say ? 

But the first is definitely doable, just more steps.

**Comment by yihui** [comment]
Yes, I agree the second option is better.

**Comment by yihui** [comment]
Actually I think it's possible to repackage all of them into zip/tar.gz/tgz [under `ubuntu-latest`](https://github.com/rstudio/tinytex/blob/afb10f301bb89bbb1a863876c66f15adecec3a49/.github/workflows/build.yaml#L271-L274) using `7zip`. That means we download the zip from quarto, unzip it, and compress the tinitex executables individually via 7zip.

**Comment by cderv** [comment]
Oh ok. 

> That means we download the zip from quarto, unzip it, and compress the tinitex executables individually via 7zip.

I was at the compress step. i'll look at 7zip command.

**Comment by cderv** [comment]
Can I create `.tgz` file with 7zip ? I don't find the info. Is it just a tar.gz with another extension ?

**Comment by cderv** [comment]
Ok I manage to do it.

**Comment by yihui** [comment]
Yes, `.tgz` identical to `tar.gz` but just another suffix.
