### ISSUE TITLE
Optimize TeX Live bundle for Windows 

### ISSUE THREAD

**Issue by cderv** [rstudio/tinytex#396]
TeX Live executables optimized by `upx` are corrupted at least for macOS, so this is not a good option.

Using the `xz` format can significantly cut the size. This is the way I have chosen for `TinyTeX-2` on macOS and Ubuntu. I think it should be good for a few years.

However, the size of the Windows bundle looks concerning. I feel it may blow up this year, so we need to take a sooner action. One solution is to use `7zip` to create a self-extracting archive:

```ps
7z a -sfx TinyTeX-2.exe $Env:APPDATA\\TinyTeX
```

@cderv I'll leave it to you to check the size of the `exe` file. I think it should be much better than `zip`. I regret not having thought of using `sfx` earlier.

Assuming we switch from `TinyTeX-2.zip` to `TinyTeX-2.exe`, I think we only need to tweak the installation scripts in three places:

https://github.com/rstudio/tinytex/blob/142cb3e8a69b4338378c61d3b7f12c0f1e6c7ec2/tools/install-bin-windows.bat#L36
https://github.com/rstudio/tinytex/blob/142cb3e8a69b4338378c61d3b7f12c0f1e6c7ec2/R/install.R#L436
https://github.com/rstudio/tinytex/blob/142cb3e8a69b4338378c61d3b7f12c0f1e6c7ec2/R/install.R#L452

_Originally posted by @yihui in https://github.com/rstudio/tinytex/issues/394#issuecomment-1370518587_

**Comment by cderv** [comment]
> I think it should be much better than zip. I regret not having thought of using sfx earlier.

@yihui what makes you think sfx with self-extraction is smaller ? I feel on Windows than doing an exe means that the tools necessary for extract will be bundled in the archive - which will increase the size. 

I'll do some comparaison with zip size.

**Comment by yihui** [comment]
Yes, bundling the extracting tool will increase the size, but on the other hand, sfx means you can use better compression methods such as `7z` to get a significantly smaller archive than using the `zip` format.

https://en.wikipedia.org/wiki/Self-extracting_archive

> Also, since the self-extracting archives must include executable code to handle the extraction of the contained archive file, they are slightly larger than the original archive.

If I understand correctly, the "executable code" here doesn't' mean the whole `7zip`, but only a (small) portion of it for extraction. This shouldn't be of concern especially because our archive is huge compared to the size of `7zip` itself.

**Comment by cderv** [comment]
So SFX creation seems to be a good idea. We are a 1.36 Gb against 1.93 Gb for current zip. 

I'll modify the script for installation now.

**Comment by cderv** [comment]
@yihui is there a way to maybe update caching at your service yihui.org that serve the gh script ? 

This `https://yihui.name/gh/tinytex/tools/install-bin-windows.bat` does not point to the latest script following merged PR. 

`setup-tinytex` uses it, and it is currently broken for TinyTeX-2 on windows now (probably no one uses that but should be working anyway) 

https://github.com/r-lib/actions/blob/33d9fe4e020f7729066594428613cd70fefbe334/setup-tinytex/src/setup-tinytex.ts#LL91C6-L91C65

**Comment by yihui** [comment]
> @yihui is there a way to maybe update caching at your service yihui.org that serve the gh script ?

It's not because of cache, but because we transferred the repo to rstudio last year, and I didn't realize that I need to reconnect Netlify with this repo. I just did it, and all the scripts should be good now.

> (I am currently testing [every bundle through github action](https://github.com/cderv/test-actions/actions/runs/3893286468) - maybe we want to do that regularly like at least once a month ?)

Yes, good idea.

**Comment by cderv** [comment]
> It's not because of cache, but because we transferred the repo to rstudio last year, and I didn't realize that I need to reconnect Netlify with this repo. I just did it, and all the scripts should be good now.

Oh glad we found this now ! 😅

**Comment by yihui** [comment]
> I'll probably put it in TinyTeX Release if that is ok. Seems better place than in TinyTeX repo itself

Yes, the `tinytex-releases` repo sounds like a better place.
