### ISSUE TITLE
说明文档里六脚贴里面的网址是否需要更新下？

### ISSUE THREAD

**Issue by chuxinyuan** [rstudio/tinytex#438]
如题。或者干脆不要那个网址得了。

**Comment by yihui** [comment]
这种问题真是杀时间啊，所以后来我根本就不想给我的包加六角贴了……

这个六角贴是 @haozhu233 设计的，不知道他是否还留着源文件。如果还在的话，我觉得去掉网址会好一点，万一十年后公司又改名了呢。

**Comment by haozhu233** [comment]
[tinytex_updated.zip](https://github.com/rstudio/tinytex/files/14654395/tinytex_updated.zip)

在电脑里找了一圈没找到，还好之前发了Curtis一份，上面这份是改好的

**Comment by chuxinyuan** [comment]
> 这种问题真是杀时间啊，所以后来我根本就不想给我的包加六角贴了……

我原以为这个六脚贴是用代码生成的，后期的修改只需要稍稍修改下代码。
