### ISSUE TITLE
Locale 'Chinese (Simplified)_China.936' is unsupported, and may crash the interpreter.

### ISSUE THREAD

**Issue by Raspberrypi4b** [rstudio/tinytex#439]
Rmarkdown appears  Locale 'Chinese (Simplified)_China.936' is unsupported, and may crash the interpreter when exporting a pdf file.

**Comment by cderv** [comment]
Hi 

Can you please add more information about the context ? document used, package used, LaTeX distribution as you mentioned latex , and any other useful information that would help us look into this. 

This also has been posted at 
* https://github.com/rstudio/tinytex-releases/issues/43

and is a duplicated; There is not much information there unfortunately for us to look closer into this.

**Comment by Raspberrypi4b** [comment]
> Hi
> 
> Can you please add more information about the context ? document used, package used, LaTeX distribution as you mentioned latex , and any other useful information that would help us look into this.
> 
> This also has been posted at
> 
> * [Locale 'Chinese (Simplified)_China.936' is unsupported, and may crash the interpreter. tinytex-releases#43](https://github.com/rstudio/tinytex-releases/issues/43)
> 
> and is a duplicated; There is not much information there unfortunately for us to look closer into this.

I've solved it, thank you for your reply

**Comment by cderv** [comment]
> I've solved it, thank you for your reply

Glad it works now. 

Don't hesite to share solution if this can help others - it has been two report about this in two repos so it seems it is not isolated issue.

**Comment by Raspberrypi4b** [comment]
> > I've solved it, thank you for your reply
> 
> Glad it works now.
> 
> Don't hesite to share solution if this can help others - it has been two report about this in two repos so it seems it is not isolated issue.
[wendang.md](https://github.com/rstudio/tinytex/files/14773161/wendang.md)

**Comment by Raspberrypi4b** [comment]
> > 我已经解决了，谢谢你的回复
> 
> 很高兴它现在起作用了。
> 
> 如果这可以帮助其他人，请不要犹豫分享解决方案 - 在两个回购中已经有两份关于此的报告，所以这似乎不是孤立的问题。

[wendang.pdf](https://github.com/rstudio/tinytex/files/14773171/wendang.pdf)

**Comment by Raspberrypi4b** [comment]
> > 我已经解决了，谢谢你的回复
> 
> 很高兴它现在起作用了。
> 
> 如果这可以帮助其他人，请不要犹豫分享解决方案 - 在两个回购中已经有两份关于此的报告，所以这似乎不是孤立的问题。

I've made the solution a pdf document：
[wendang.pdf](https://github.com/rstudio/tinytex/files/14773272/wendang.pdf)

**Comment by yihui** [comment]
@Raspberrypi4b Thanks! That's exactly what I recommended in https://github.com/rstudio/tinytex-releases/issues/43.
