### ISSUE TITLE
After git-latexdiff is installed `git latexdiff` is not recognized in terminal on Windows

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/tinytex#440]
I was able to do `tinytex::tlmgr_install("git-latexdiff") on Windows for [git-latexdiff package](https://gitlab.com/git-latexdiff/git-latexdiff).

For some reason, however, `git latexdiff` command does not work in terminal on Windows. I was wondering if this had to do with the installation path.

The vanilla `latexdiff` command works though after installing `tinytex::tlmgr_install("latexdiff")`.

**Comment by cderv** [comment]
This must only be a PATH issue. Especially on Windows as `git-latexdiff` is only to be used with Git Bash as they document (https://gitlab.com/git-latexdiff/git-latexdiff#on-windows). 

If I try the installation and search for `git-latexdiff` on my environment, I can see that it is available in TinyTeX installation directories at `TinyTeX\texmf-dist\scripts\git-latexdiff` - this `scripts` folder is not in PATH for me on windows, as usual windows tools for TeX Live are in `TinyTeX\bin\windows\`. 

So you just need to add the correct paths to the script in the environment you want to run it by adapting your PATH.
