### ISSUE TITLE
Daily release failing on macOS

### ISSUE THREAD

**Issue by yihui** [rstudio/tinytex#442]
https://github.com/rstudio/tinytex/actions

I guess it's because the total size of all TinyTeX-* bundles is exceeding 2Gb on macOS. Perhaps we should upload them separately? https://github.com/rstudio/tinytex/blob/main/.github/workflows/build.yaml#L272

**Comment by cderv** [comment]
It seems latest run passed in 1 attempt 🤔 https://github.com/rstudio/tinytex/actions/runs/9056655986

We could indeed update each assets after the other insead of all at once. 

I'll wait to see if it happens again soon or if it was something else

**Comment by cderv** [comment]
It failed again today. I triggered it another time to see 
https://github.com/rstudio/tinytex/actions/runs/9073158714/attempts/1

**Comment by cderv** [comment]
It happend again. I added debug information for the `gh` api calls now in https://github.com/rstudio/tinytex/actions/runs/9084874566/job/24966857253#step:10:20

So we have more details on what it the problem. I need to read the log now 😅

**Comment by cderv** [comment]
This is solved now. It was a problem of timeout in our retry action step. We had 5 minutes, but the upload now takes more time. 

All set with 10 minutes timeout for now.
