### ISSUE TITLE
tinytex installation issue

### ISSUE THREAD

**Issue by Maggie647** [rstudio/tinytex#449]
Hi,
I've already installed the tinytex using install.packages

```r
install.packages("tinytex)
tinytex::install_tinytex()
``` 
And I also received that it was installed successful (?), although got some notifications about English_United States not supported. Then I tried to knit my R markdown file into pdf, but I got the problem as in the screen shot.
![Screenshot 2024-09-25 101713](https://github.com/user-attachments/assets/310a18c5-a259-412d-8551-e285bb622f57)

Then I though maybe the installation was not successful, so I repeated the codes in the beginning again, but I was told that tinytex was already installed, if I want to install it again. I'm using the Windows, no idea how to figure it out.

**Comment by yihui** [comment]
Don't put these two lines of code in your Rmd document---you don't really want to run them every single time you knit the document. There is no need to install tinytex or TinyTeX over and over again. You only need to do it once (in the R console).

After installation, quit RStudio and re-open it. Check `tinytex::is_tinytex()` (should be `TRUE`).
